### ISSUE TITLE
Incorrect author for spotify case study

### ISSUE THREAD

**Issue by ddahlmeier** [chiphuyen/dmls-book#9]
I spotted what seems to be a minor mistake on the collection of case studies at https://github.com/chiphuyen/dmls-book/blob/main/resources.md

The author of the spotify case study is Umesh .A Bhat.

[Spotify’s Discover Weekly: How machine learning finds your new music](https://hackernoon.com/spotifys-discover-weekly-how-machine-learning-finds-your-new-music-19a41ab76efe) (Umesh .A Bhat, 2017)

But when opening the blog article, the author is Sophia Ciocca

**Comment by chiphuyen** [comment]
good catch. updated. thanks @ddahlmeier!
